# ??? OAuth ??
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            # REST API KEY
            client-id: 'ca7f8ed6e2319aed7b48c35dcdbf5d2d'
            # ???? : ? ?????? > ?? > Client Key
            client-secret: 'epQzSMpRYGwkh85q0EduqQKHKLkQeZ0T'
            # ???? ???? ??? ? ??? ??? URL
            redirect-uri: 'http://localhost:8080/login/oauth2/code/kakao'
            # authorization-grant-type : ?? ???? ???? ??? ??? ??? ?, ??? ???? ?? ??
            authorization-grant-type: authorization_code
            # ??? ?? ?? ?? : ??? ???, ???, ??? ??
            scope: profile_nickname, account_email, profile_image
            # ?????? ???? ?? ??
            client-name: Kakao
            # ?? ??? ?? ?, ??? ?? ???
            client-authentication-method: client_secret_post
        provider:
          kakao:
            # ?? ?? ?? URI(??? ????)
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            # ??? ?? ?? URI(??? ????)
            token-uri: https://kauth.kakao.com/oauth/token
            # ??? ?? ?? URL(??? ??? ??)
            user-info-uri: https://kapi.kakao.com/v2/user/me
            # ??? ?? ?? ?? ? ??
            user-name-attribute: id