spring:
  profiles:
    active: "local"
    group:
      "local": "localDB, devPort, secret, web-mvc"
      "dev": "devDB, devPort, secret, web-mvc"
      "prod": "prodDB, prodPort, secret, web-mvc"

  # 파일 업로드 용량 설정
  servlet:
    multipart:
      max-file-size: 5MB # 파일의 용량 제한
      max-request-size: 10MB # 전체 최대 크기 용량 제한

# 카카오 rest api 방식 설정
oauth:
  kakao:
    url:
      auth: "https://kauth.kakao.com/oauth/token"
      api : "https://kapi.kakao.com/v2/user/me"
    client-id : ${OAUTH_KAKAO_CLIENT_ID}
    redirect-url: ${OAUTH_KAKAO_REDIRECT_URL}

# s3 설정
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
      credentials :
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}
      region :
        static: ap-northeast-2
      stack:
        auto: false

---

spring:
  config:
    activate:
      on-profile: "localDB"

  datasource:
    url: ${DATASOURCE_URL_LOCAL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql

---

spring:
  config:
    activate:
      on-profile: "devDB"

  datasource:
    url: ${DATASOURCE_URL_DEV}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql

---

spring:
  config:
    activate:
      on-profile: "prodDB"

  datasource:
    url: ${DATASOURCE_URL_PROD}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
  sql:
    init:
      platform: mysql

---

spring:
  config:
    activate:
      on-profile: "devPort"

server:
  port: 9000

---

spring:
  config:
    activate:
      on-profile: "prodPort"

server:
  port: 9001

---

spring:
  config:
    activate:
      on-profile: "secret"

secret:
  jwt-secret-key: ${JWT_SECRET_KEY}
  jwt-expired-in: ${JWT_EXPIRED_IN}

---

spring:
  config:
    activate:
      on-profile: "web-mvc"

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  messages:
    basename: errors

